CREATE TABLE PRODUITS (ID_NFC int PRIMARY KEY,name VARCHAR(30));
CREATE TABLE TEMPERATURES (RELEVE_ID int PRIMARY KEY AUTO_INCREMENT, TEMPERATURE int, DATE_RELEVE datetime);
CREATE TABLE STOCK (STOCK_ID int PRIMARY KEY AUTO_INCREMENT,PRODUIT int NOT NULL, DATE_PEREMPTION date, DATE_ACHAT date,constraint type_produit FOREIGN KEY (PRODUIT) REFERENCES PRODUITS(ID_NFC));